# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake 2.8\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "C:\Program Files (x86)\CMake 2.8\bin\cmake-gui.exe"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Build\lib\osmium

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Build\lib\osmium

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake 2.8\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	"C:\Program Files (x86)\CMake 2.8\bin\cpack.exe" --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	"C:\Program Files (x86)\CMake 2.8\bin\cpack.exe" --config ./CPackSourceConfig.cmake D:/Build/lib/osmium/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	"C:\Program Files (x86)\CMake 2.8\bin\ctest.exe" --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Build\lib\osmium\CMakeFiles D:\Build\lib\osmium\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Build\lib\osmium\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nodedensity

# Build rule for target.
nodedensity: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 nodedensity
.PHONY : nodedensity

# fast build rule for target.
nodedensity/fast:
	$(MAKE) -f examples\CMakeFiles\nodedensity.dir\build.make examples/CMakeFiles/nodedensity.dir/build
.PHONY : nodedensity/fast

#=============================================================================
# Target rules for targets named osmium_convert

# Build rule for target.
osmium_convert: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 osmium_convert
.PHONY : osmium_convert

# fast build rule for target.
osmium_convert/fast:
	$(MAKE) -f examples\CMakeFiles\osmium_convert.dir\build.make examples/CMakeFiles/osmium_convert.dir/build
.PHONY : osmium_convert/fast

#=============================================================================
# Target rules for targets named osmium_debug

# Build rule for target.
osmium_debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 osmium_debug
.PHONY : osmium_debug

# fast build rule for target.
osmium_debug/fast:
	$(MAKE) -f examples\CMakeFiles\osmium_debug.dir\build.make examples/CMakeFiles/osmium_debug.dir/build
.PHONY : osmium_debug/fast

#=============================================================================
# Target rules for targets named osmium_find_bbox

# Build rule for target.
osmium_find_bbox: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 osmium_find_bbox
.PHONY : osmium_find_bbox

# fast build rule for target.
osmium_find_bbox/fast:
	$(MAKE) -f examples\CMakeFiles\osmium_find_bbox.dir\build.make examples/CMakeFiles/osmium_find_bbox.dir/build
.PHONY : osmium_find_bbox/fast

#=============================================================================
# Target rules for targets named osmium_mpdump

# Build rule for target.
osmium_mpdump: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 osmium_mpdump
.PHONY : osmium_mpdump

# fast build rule for target.
osmium_mpdump/fast:
	$(MAKE) -f examples\CMakeFiles\osmium_mpdump.dir\build.make examples/CMakeFiles/osmium_mpdump.dir/build
.PHONY : osmium_mpdump/fast

#=============================================================================
# Target rules for targets named osmium_progress

# Build rule for target.
osmium_progress: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 osmium_progress
.PHONY : osmium_progress

# fast build rule for target.
osmium_progress/fast:
	$(MAKE) -f examples\CMakeFiles\osmium_progress.dir\build.make examples/CMakeFiles/osmium_progress.dir/build
.PHONY : osmium_progress/fast

#=============================================================================
# Target rules for targets named osmium_range_from_history

# Build rule for target.
osmium_range_from_history: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 osmium_range_from_history
.PHONY : osmium_range_from_history

# fast build rule for target.
osmium_range_from_history/fast:
	$(MAKE) -f examples\CMakeFiles\osmium_range_from_history.dir\build.make examples/CMakeFiles/osmium_range_from_history.dir/build
.PHONY : osmium_range_from_history/fast

#=============================================================================
# Target rules for targets named osmium_relation_members

# Build rule for target.
osmium_relation_members: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 osmium_relation_members
.PHONY : osmium_relation_members

# fast build rule for target.
osmium_relation_members/fast:
	$(MAKE) -f examples\CMakeFiles\osmium_relation_members.dir\build.make examples/CMakeFiles/osmium_relation_members.dir/build
.PHONY : osmium_relation_members/fast

#=============================================================================
# Target rules for targets named osmium_sizeof

# Build rule for target.
osmium_sizeof: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 osmium_sizeof
.PHONY : osmium_sizeof

# fast build rule for target.
osmium_sizeof/fast:
	$(MAKE) -f examples\CMakeFiles\osmium_sizeof.dir\build.make examples/CMakeFiles/osmium_sizeof.dir/build
.PHONY : osmium_sizeof/fast

#=============================================================================
# Target rules for targets named osmium_store_and_debug

# Build rule for target.
osmium_store_and_debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 osmium_store_and_debug
.PHONY : osmium_store_and_debug

# fast build rule for target.
osmium_store_and_debug/fast:
	$(MAKE) -f examples\CMakeFiles\osmium_store_and_debug.dir\build.make examples/CMakeFiles/osmium_store_and_debug.dir/build
.PHONY : osmium_store_and_debug/fast

#=============================================================================
# Target rules for targets named osmium_time

# Build rule for target.
osmium_time: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 osmium_time
.PHONY : osmium_time

# fast build rule for target.
osmium_time/fast:
	$(MAKE) -f examples\CMakeFiles\osmium_time.dir\build.make examples/CMakeFiles/osmium_time.dir/build
.PHONY : osmium_time/fast

#=============================================================================
# Target rules for targets named osmium_to_postgis

# Build rule for target.
osmium_to_postgis: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 osmium_to_postgis
.PHONY : osmium_to_postgis

# fast build rule for target.
osmium_to_postgis/fast:
	$(MAKE) -f examples\CMakeFiles\osmium_to_postgis.dir\build.make examples/CMakeFiles/osmium_to_postgis.dir/build
.PHONY : osmium_to_postgis/fast

#=============================================================================
# Target rules for targets named osmium_toogr

# Build rule for target.
osmium_toogr: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 osmium_toogr
.PHONY : osmium_toogr

# fast build rule for target.
osmium_toogr/fast:
	$(MAKE) -f examples\CMakeFiles\osmium_toogr.dir\build.make examples/CMakeFiles/osmium_toogr.dir/build
.PHONY : osmium_toogr/fast

#=============================================================================
# Target rules for targets named osmium_toogr2

# Build rule for target.
osmium_toogr2: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 osmium_toogr2
.PHONY : osmium_toogr2

# fast build rule for target.
osmium_toogr2/fast:
	$(MAKE) -f examples\CMakeFiles\osmium_toogr2.dir\build.make examples/CMakeFiles/osmium_toogr2.dir/build
.PHONY : osmium_toogr2/fast

#=============================================================================
# Target rules for targets named osmium_toshape

# Build rule for target.
osmium_toshape: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 osmium_toshape
.PHONY : osmium_toshape

# fast build rule for target.
osmium_toshape/fast:
	$(MAKE) -f examples\CMakeFiles\osmium_toshape.dir\build.make examples/CMakeFiles/osmium_toshape.dir/build
.PHONY : osmium_toshape/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f test\CMakeFiles\Continuous.dir\build.make test/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f test\CMakeFiles\ContinuousBuild.dir\build.make test/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f test\CMakeFiles\ContinuousConfigure.dir\build.make test/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f test\CMakeFiles\ContinuousCoverage.dir\build.make test/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f test\CMakeFiles\ContinuousMemCheck.dir\build.make test/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f test\CMakeFiles\ContinuousStart.dir\build.make test/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f test\CMakeFiles\ContinuousSubmit.dir\build.make test/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f test\CMakeFiles\ContinuousTest.dir\build.make test/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f test\CMakeFiles\ContinuousUpdate.dir\build.make test/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f test\CMakeFiles\Experimental.dir\build.make test/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f test\CMakeFiles\ExperimentalBuild.dir\build.make test/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f test\CMakeFiles\ExperimentalConfigure.dir\build.make test/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f test\CMakeFiles\ExperimentalCoverage.dir\build.make test/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f test\CMakeFiles\ExperimentalMemCheck.dir\build.make test/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f test\CMakeFiles\ExperimentalStart.dir\build.make test/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f test\CMakeFiles\ExperimentalSubmit.dir\build.make test/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f test\CMakeFiles\ExperimentalTest.dir\build.make test/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f test\CMakeFiles\ExperimentalUpdate.dir\build.make test/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f test\CMakeFiles\Nightly.dir\build.make test/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f test\CMakeFiles\NightlyBuild.dir\build.make test/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f test\CMakeFiles\NightlyConfigure.dir\build.make test/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f test\CMakeFiles\NightlyCoverage.dir\build.make test/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f test\CMakeFiles\NightlyMemCheck.dir\build.make test/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f test\CMakeFiles\NightlyMemoryCheck.dir\build.make test/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f test\CMakeFiles\NightlyStart.dir\build.make test/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f test\CMakeFiles\NightlySubmit.dir\build.make test/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f test\CMakeFiles\NightlyTest.dir\build.make test/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f test\CMakeFiles\NightlyUpdate.dir\build.make test/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named test_filter

# Build rule for target.
test_filter: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_filter
.PHONY : test_filter

# fast build rule for target.
test_filter/fast:
	$(MAKE) -f test\t\tags\CMakeFiles\test_filter.dir\build.make test/t/tags/CMakeFiles/test_filter.dir/build
.PHONY : test_filter/fast

#=============================================================================
# Target rules for targets named test_regex_filter

# Build rule for target.
test_regex_filter: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_regex_filter
.PHONY : test_regex_filter

# fast build rule for target.
test_regex_filter/fast:
	$(MAKE) -f test\t\tags\CMakeFiles\test_regex_filter.dir\build.make test/t/tags/CMakeFiles/test_regex_filter.dir/build
.PHONY : test_regex_filter/fast

#=============================================================================
# Target rules for targets named test_tag

# Build rule for target.
test_tag: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_tag
.PHONY : test_tag

# fast build rule for target.
test_tag/fast:
	$(MAKE) -f test\t\tags\CMakeFiles\test_tag.dir\build.make test/t/tags/CMakeFiles/test_tag.dir/build
.PHONY : test_tag/fast

#=============================================================================
# Target rules for targets named test_to_string

# Build rule for target.
test_to_string: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_to_string
.PHONY : test_to_string

# fast build rule for target.
test_to_string/fast:
	$(MAKE) -f test\t\tags\CMakeFiles\test_to_string.dir\build.make test/t/tags/CMakeFiles/test_to_string.dir/build
.PHONY : test_to_string/fast

#=============================================================================
# Target rules for targets named test_timestamp

# Build rule for target.
test_timestamp: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_timestamp
.PHONY : test_timestamp

# fast build rule for target.
test_timestamp/fast:
	$(MAKE) -f test\t\utils\CMakeFiles\test_timestamp.dir\build.make test/t/utils/CMakeFiles/test_timestamp.dir/build
.PHONY : test_timestamp/fast

#=============================================================================
# Target rules for targets named test_bounds

# Build rule for target.
test_bounds: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_bounds
.PHONY : test_bounds

# fast build rule for target.
test_bounds/fast:
	$(MAKE) -f test\t\osm\CMakeFiles\test_bounds.dir\build.make test/t/osm/CMakeFiles/test_bounds.dir/build
.PHONY : test_bounds/fast

#=============================================================================
# Target rules for targets named test_node

# Build rule for target.
test_node: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_node
.PHONY : test_node

# fast build rule for target.
test_node/fast:
	$(MAKE) -f test\t\osm\CMakeFiles\test_node.dir\build.make test/t/osm/CMakeFiles/test_node.dir/build
.PHONY : test_node/fast

#=============================================================================
# Target rules for targets named test_position

# Build rule for target.
test_position: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_position
.PHONY : test_position

# fast build rule for target.
test_position/fast:
	$(MAKE) -f test\t\osm\CMakeFiles\test_position.dir\build.make test/t/osm/CMakeFiles/test_position.dir/build
.PHONY : test_position/fast

#=============================================================================
# Target rules for targets named test_way_node

# Build rule for target.
test_way_node: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_way_node
.PHONY : test_way_node

# fast build rule for target.
test_way_node/fast:
	$(MAKE) -f test\t\osm\CMakeFiles\test_way_node.dir\build.make test/t/osm/CMakeFiles/test_way_node.dir/build
.PHONY : test_way_node/fast

#=============================================================================
# Target rules for targets named test_way_node_list

# Build rule for target.
test_way_node_list: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_way_node_list
.PHONY : test_way_node_list

# fast build rule for target.
test_way_node_list/fast:
	$(MAKE) -f test\t\osm\CMakeFiles\test_way_node_list.dir\build.make test/t/osm/CMakeFiles/test_way_node_list.dir/build
.PHONY : test_way_node_list/fast

#=============================================================================
# Target rules for targets named test_filename

# Build rule for target.
test_filename: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_filename
.PHONY : test_filename

# fast build rule for target.
test_filename/fast:
	$(MAKE) -f test\t\osmfile\CMakeFiles\test_filename.dir\build.make test/t/osmfile/CMakeFiles/test_filename.dir/build
.PHONY : test_filename/fast

#=============================================================================
# Target rules for targets named test_linestring_geometry

# Build rule for target.
test_linestring_geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_linestring_geometry
.PHONY : test_linestring_geometry

# fast build rule for target.
test_linestring_geometry/fast:
	$(MAKE) -f test\t\geometry\CMakeFiles\test_linestring_geometry.dir\build.make test/t/geometry/CMakeFiles/test_linestring_geometry.dir/build
.PHONY : test_linestring_geometry/fast

#=============================================================================
# Target rules for targets named test_point_geometry

# Build rule for target.
test_point_geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_point_geometry
.PHONY : test_point_geometry

# fast build rule for target.
test_point_geometry/fast:
	$(MAKE) -f test\t\geometry\CMakeFiles\test_point_geometry.dir\build.make test/t/geometry/CMakeFiles/test_point_geometry.dir/build
.PHONY : test_point_geometry/fast

#=============================================================================
# Target rules for targets named test_polygon_geometry

# Build rule for target.
test_polygon_geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_polygon_geometry
.PHONY : test_polygon_geometry

# fast build rule for target.
test_polygon_geometry/fast:
	$(MAKE) -f test\t\geometry\CMakeFiles\test_polygon_geometry.dir\build.make test/t/geometry/CMakeFiles/test_polygon_geometry.dir/build
.PHONY : test_polygon_geometry/fast

#=============================================================================
# Target rules for targets named test_geometry_geos

# Build rule for target.
test_geometry_geos: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_geometry_geos
.PHONY : test_geometry_geos

# fast build rule for target.
test_geometry_geos/fast:
	$(MAKE) -f test\t\geometry_geos\CMakeFiles\test_geometry_geos.dir\build.make test/t/geometry_geos/CMakeFiles/test_geometry_geos.dir/build
.PHONY : test_geometry_geos/fast

#=============================================================================
# Target rules for targets named test_geometry_ogr

# Build rule for target.
test_geometry_ogr: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_geometry_ogr
.PHONY : test_geometry_ogr

# fast build rule for target.
test_geometry_ogr/fast:
	$(MAKE) -f test\t\geometry_ogr\CMakeFiles\test_geometry_ogr.dir\build.make test/t/geometry_ogr/CMakeFiles/test_geometry_ogr.dir/build
.PHONY : test_geometry_ogr/fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... package
	@echo ... package_source
	@echo ... rebuild_cache
	@echo ... test
	@echo ... nodedensity
	@echo ... osmium_convert
	@echo ... osmium_debug
	@echo ... osmium_find_bbox
	@echo ... osmium_mpdump
	@echo ... osmium_progress
	@echo ... osmium_range_from_history
	@echo ... osmium_relation_members
	@echo ... osmium_sizeof
	@echo ... osmium_store_and_debug
	@echo ... osmium_time
	@echo ... osmium_to_postgis
	@echo ... osmium_toogr
	@echo ... osmium_toogr2
	@echo ... osmium_toshape
	@echo ... Continuous
	@echo ... ContinuousBuild
	@echo ... ContinuousConfigure
	@echo ... ContinuousCoverage
	@echo ... ContinuousMemCheck
	@echo ... ContinuousStart
	@echo ... ContinuousSubmit
	@echo ... ContinuousTest
	@echo ... ContinuousUpdate
	@echo ... Experimental
	@echo ... ExperimentalBuild
	@echo ... ExperimentalConfigure
	@echo ... ExperimentalCoverage
	@echo ... ExperimentalMemCheck
	@echo ... ExperimentalStart
	@echo ... ExperimentalSubmit
	@echo ... ExperimentalTest
	@echo ... ExperimentalUpdate
	@echo ... Nightly
	@echo ... NightlyBuild
	@echo ... NightlyConfigure
	@echo ... NightlyCoverage
	@echo ... NightlyMemCheck
	@echo ... NightlyMemoryCheck
	@echo ... NightlyStart
	@echo ... NightlySubmit
	@echo ... NightlyTest
	@echo ... NightlyUpdate
	@echo ... test_filter
	@echo ... test_regex_filter
	@echo ... test_tag
	@echo ... test_to_string
	@echo ... test_timestamp
	@echo ... test_bounds
	@echo ... test_node
	@echo ... test_position
	@echo ... test_way_node
	@echo ... test_way_node_list
	@echo ... test_filename
	@echo ... test_linestring_geometry
	@echo ... test_point_geometry
	@echo ... test_polygon_geometry
	@echo ... test_geometry_geos
	@echo ... test_geometry_ogr
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

